chess/urls.py
from django.urls import path

from .views import GamesList, GameDetails, TournamentsList, TournamentDetails

urlpatterns = [
    path('', GamesList.as_view(), name='index'),
    path('game/<int:pk>', GameDetails.as_view(), name='game'),
    path('tournaments', TournamentsList.as_view(), name='tournaments'),
    path('tournament/<int:pk>', TournamentDetails.as_view(), name='tournament'),
]

chess_app/urls.py
from django.conf.urls import url
from django.urls import path

from chess_game_viewer import settings
from .views import GamesList, GameDetails, TournamentsList, TournamentDetails, parse_pgn, download_pgn
from django.views.generic import TemplateView


urlpatterns = [
    path('', GamesList.as_view(), name='index'),
    path('game/<int:pk>', GameDetails.as_view(), name='game'),
    path('tournaments/', TournamentsList.as_view(), name='tournaments'),
    path('tournament/<int:pk>', TournamentDetails.as_view(), name='tournament'),
    path('parser/', parse_pgn, name='parser'),
    path('pgn/<int:pgn_id>', download_pgn, name='pgn'),
    path('board', TemplateView.as_view(template_name="board.html"),
                   name='board'),
]

chess_game_viewer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('chess_app.urls', 'chess_viewer'), namespace="chess_viewer")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chess_app/models.py
from django.db import models

from chess_app.lookups import OnlyYearAndMonth
from django.core.validators import FileExtensionValidator


class Parse(models.Model):
    upload = models.FileField(upload_to="", validators=[FileExtensionValidator(['pgn'])])

    def __str__(self):
        return '%s' % (self.upload)


class Tournament(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=5000, null=True, blank=True)
    type = models.CharField(max_length=1, null=True)
    time = models.DecimalField(max_digits=5, decimal_places=1, default=0, null=True, blank=True)
    time_add = models.DecimalField(max_digits=5, decimal_places=1, default=0, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    link = models.CharField(max_length=200, null=True, blank=True)

    models.DateField.register_lookup(OnlyYearAndMonth)

    def __str__(self):
        return self.name


class Player(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    club = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class PGN(models.Model):
    pgn = models.TextField(max_length=5000)


class Game(models.Model):
    white_player = models.ForeignKey(Player, related_name='white', on_delete=models.CASCADE)
    black_player = models.ForeignKey(Player, related_name='black', on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    result = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True)
    round = models.IntegerField(default=1, null=True, blank=True)
    pgn = models.ForeignKey(PGN, on_delete=models.CASCADE, null=True, blank=True)
    preview = models.TextField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.white_player.first_name + ' ' + self.white_player.last_name + ":" + self.black_player.first_name + ' ' + self.black_player.last_name + ' id:' + str(
            self.id)

chess_app/forms.py
from django import forms
from chess_app.models import PGN, Tournament


class PgnForm(forms.ModelForm):
    class Meta:
        model = PGN
        fields = ('pgn',)


class TournamentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(TournamentForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['name'].required = False
        self.fields['type'].required = False

    class Meta:
        model = Tournament
        fields = ('name', 'description', 'type', 'time', 'time_add', 'date', 'city', 'link',)
        labels = {
            'name': 'Nazwa',
            'description': 'Opis',
            'type': 'Typ',
            'time': 'Czas',
            'time_add': 'Doliczony czas gry',
            'date': 'Data',
            'city': 'Miejscowość',
            'link': 'Link'
        }
        TYPE_CHOICES = (
            ('', 'Wybierz typ zawodów'),
            ('k', 'klasyczne'),
            ('s', 'szybkie'),
            ('b', 'błyskawiczne'),
        )
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'type': forms.Select(choices=TYPE_CHOICES, attrs={'class': 'form-control'}),
            'time': forms.NumberInput(attrs={'class': 'form-control', 'step': "0.01"}),
            'time_add': forms.NumberInput(attrs={'class': 'form-control', 'step': "0.01"}),
            'date': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control',
                                                              'placeholder': 'Select a date',
                                                              'type': 'date'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'link': forms.TextInput(attrs={'class': 'form-control'}),
        }

chess_app/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django_filters.views import FilterView
from .forms import TournamentForm
from .filters import TournamentsListFilter, GamesListFilter
from .getdata import parse_data, get_tournament_data
from .models import Tournament, Game, PGN
from dateutil.parser import parse
from django.db.models import F


class TournamentsList(FilterView):
    model = Tournament
    template_name = "../templates/tournament_list.html"
    paginate_by = 10
    ordering = [F('date').desc(nulls_last=True), '-id']

    filterset_class = TournamentsListFilter

    sel_op = {
        '': '...',
        'k': 'Klasyczne',
        's': 'Szybkie',
        'b': 'Błyskawiczne'
    }

    def get_context_data(self, **kwargs):
        return super(TournamentsList, self).get_context_data(select_options=self.sel_op, **kwargs)


class TournamentDetails(DetailView):
    model = Tournament
    template_name = "../templates/tournament.html"

    # paginate_by = 5
    # ordering = ['-id']

    def get_context_data(self, **kwargs):
        games = list(Game.objects.filter(tournament_id=self.object.id).order_by("-id"))

        games_grouped = dict()
        for game in games:
            r = game.round
            if r is None:
                r = 0
            if games_grouped.get(r):
                games_grouped[r].append(game)
            else:
                games_grouped[r] = [game]
                
        context = super(TournamentDetails, self).get_context_data(object_list=sorted(games_grouped.items()), **kwargs)
        return context


class GamesList(FilterView):
    model = Game
    template_name = "../templates/game_list.html"
    paginate_by = 10
    ordering = ['-id']

    filterset_class = GamesListFilter

    sel_op = {
        '': '...',
        'k': 'Klasyczne',
        's': 'Szybkie',
        'b': 'Błyskawiczne'
    }

    def get_context_data(self, **kwargs):
        return super(GamesList, self).get_context_data(select_options=self.sel_op, **kwargs)


class GameDetails(DetailView):
    model = Game
    template_name = "../templates/game.html"

    def get_context_data(self, **kwargs):

        similar_random = False
        similar_games = []

        if self.object.tournament_id:
            similar_games = list(Game.objects.filter(tournament_id=self.object.tournament_id).order_by("round"))

        if not self.object.tournament_id or len(similar_games) < 2:
            similar_games = list(Game.objects.exclude(id=self.object.id).order_by('?')[:5])
            if(len(similar_games)) > 0:
                similar_games[0] = self.object
            similar_random = True

        current_game_id = self.object.id
        context = super(GameDetails, self).get_context_data(
            similar_games=similar_games,
            current_game_id=current_game_id,
            similar_random=similar_random,
            **kwargs)
        return context


@login_required(login_url='/admin/login/')
def parse_pgn(request):
    pgns = request.session.get('pgn')
    PgnFormSet = modelformset_factory(PGN, fields=('pgn',), extra=len(pgns))
    t_name = request.session.get("t_name")
    if t_name is not None and t_name != "" and t_name != "?":
        tmp_tournament, created = Tournament.objects.get_or_create(name=t_name)
    else:
        created = False
        tmp_tournament = None

    if created and tmp_tournament:
        description = tmp_tournament.description
        time = tmp_tournament.time
        time_add = tmp_tournament.time_add
        type = tmp_tournament.type
        link = tmp_tournament.link
    else:
        description = ""
        time = 0
        time_add = 0
        type = ""
        link = ""

    if t_name == "?":
        t_name = None

    t_date_str = request.session.get("t_date")
    t_city = request.session.get("t_city")

    if t_city == "?":
        t_city = None

    try:
        t_date = parse(t_date_str).date()
        if t_date.year < 1950:
            t_date = None
    except ValueError:
        t_date = None

    if request.method == 'POST':
        t_form = TournamentForm(request.POST)
        formset = PgnFormSet(request.POST)
        if formset.is_valid() and t_form.is_valid():
            t_cd = t_form.cleaned_data
            tournament = get_tournament_data(t_cd)
            for f in formset:
                cd = f.cleaned_data
                if not cd:
                    continue

                data = cd.get('pgn')
                parse_data(data, tournament)

            request.session['pgn'] = ""
            request.session['t_name'] = ""
            request.session['t_date'] = ""
            request.session['city'] = ""
            return redirect('/admin/chess_app/pgn')

        return render(request, 'parser.html', {'t_form': t_form, 'formset': formset})
    else:
        t_form = TournamentForm(initial={'name': t_name, 'date': t_date, 'city': t_city, 'description': description,
                                         'time': time, 'time_add': time_add, 'type': type, 'link': link})
        formset = PgnFormSet(queryset=PGN.objects.none(), initial=[{'pgn': x} for x in pgns])
        return render(request, 'parser.html', {'t_form': t_form, 'formset': formset})


def download_pgn(request, pgn_id):
    file = PGN.objects.get(id=pgn_id).pgn
    response = HttpResponse(file, content_type='application/text')
    response['Content-Disposition'] = 'attachment; filename="game.pgn"'
    return response

chess_app/templates/base.html
{% load env_extras %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>  {% block title %}Baza partii szachowych  {% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <style>
        html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 80px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  line-height: 60px;
  background-color: #f5f5f5;
}</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  </a>
    <a class="navbar-brand" href="{% url 'chess_viewer:index' %}">
    <img class="d-inline-block align-top mr-3" src={% static 'images/logo.png' %} width="30" height="30" alt="">
        Baza partii szachowych</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                {% block nav-index %}
                    <a class="nav-link" href="{% url 'chess_viewer:index' %}">Lista partii </a> {% endblock %}
            </li>
            <li class="nav-item">
                {% block nav-tournaments %}
                    <a class="nav-link" href="{% url 'chess_viewer:tournaments' %}">Turnieje</a> {% endblock %}
            </li>
        </ul>
    </div>
</nav>

<div class="container mb-5">
    {% block content %}
    {% endblock %}
</div>

<footer class="footer">
  <div class="container text-center">
      <span class="text-muted">{% get_env 'PAGE_NAME' %} © <script>document.write(new Date().getFullYear())</script> </span>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

chess_app/templates/game.html
{%  extends 'base.html' %}

{% block title %}{{ object.white_player.first_name }} {{ object.white_player.last_name }} -
             {{ object.black_player.first_name }} {{ object.black_player.last_name }}
{% endblock title %}

{% block content %}
<div class="row">
<div class="col-12 col-xl-7">
<div class="card my-3">
    <div class="card-header text-center d-inline-flex justify-content-center">
        <div class="text-right"><strong><div>{{ object.white_player.first_name }} {{ object.white_player.last_name }}</div></strong>
            <div class="small">{% if object.white_player.club %} {{ object.white_player.club }} {% endif %}</div>
        </div>
        <div class="mx-2"><b>-</b></div>
        <div class="text-left"><strong><div>{{ object.black_player.first_name }} {{ object.black_player.last_name }}</div></strong>
            <div class="small">{% if object.black_player.club %} {{ object.black_player.club }} {% endif %}</div>
        </div>
    </div>

    {%  if object.tournament %}
  <ul class="list-group list-group-flush"><strong>
     <li class="list-group-item d-flex justify-content-between align-items-center">
         <span>{{ object.tournament.name }}</span><span>{% if object.date %} {{ object.date }} {% endif %}</span>
     </li></strong>
  </ul>
    {% endif %}
<div class="d-flex align-items-center"><iframe class="mx-auto mt-3" height='750' width='{% if not request.user_agent.is_mobile %}600 {% else %}350{%  endif %}' frameborder='0' scrolling='yes' marginheight='0' marginwidth='0' src='{% url 'chess_viewer:board' %}?
pieceFont=uscf&amp;
{% if not request.user_agent.is_mobile %}
pieceSize=56&amp;&amp;
squareSize=64&amp;
{% else %}
pieceSize=38&amp;&amp;
squareSize=43&amp;
{% endif %}

lightColorHex=FFCC99&amp;
darkColorHex=CC9966&amp;
highlightMode=border&amp;
highlightColorHex=705438&amp;
highlightMoveColorHex=FFCC99&amp;
headerDisplay=centered&amp;
movesDisplay=figurine&amp;
fontHeaderSize=80pct&amp;
fontMovesSize=80pct&amp;
fontCommentsSize=80pct&amp;
autoplayMode=game&amp;
delay=3000&amp;
frameHeight=750&amp;
frameWidth={% if not request.user_agent.is_mobile %}550 {% else %}350{%  endif %}&amp;
pgnText={{ game.pgn.pgn }}'
        >

        your web browser and/or your host do not support iframes as required to display the chessboard

        </iframe>
</div>
</div>

  </div>
<div class="col-12 col-xl-5 d-flex flex-column align-items-center">
{% include "partial/similar.html" %}
<a class="btn btn-light m-3 btn-outline-info align-self-stretch" href="{% url 'chess_viewer:pgn' object.pgn.id %}">Pobierz partię</a>
</div>
</div>

    {%  if object.tournament %}
    <div class="text-center">
        <a class="btn btn-info m-3" href="{% url 'chess_viewer:tournament' object.tournament.id %}">Powrót do turnieju</a>
    </div>
    {% else %}
    <div class="text-center">
        <a class="btn btn-info m-3" href="{{  request.META.HTTP_REFERER }}">Powrót</a>
    </div>
    {% endif %}

{% endblock %}

chess_app/templates/game_list.html
{% extends 'base.html' %}
{% load get_dict_value %}

{% block nav-index %}
    <a class="nav-link active" href="{% url 'chess_viewer:index' %}">Lista partii </a>
{% endblock %}

{% block content %}
    <div class="my-4">
    <span class="text-center">
    <h2 class="mb-3">Baza partii </h2>

    </span>
        <div class="card">
            <div class="card-body">
                <form novalidate>
                    <div class="form-row d-flex justify-content-center">
                        <div class="col-md-5 mb-3">
                            <label for="gamelastname">Nazwisko</label>
                            <input type="text" class="form-control" id="gamelastname"
                                   name="name_filter"
                                   value="{{ filter.data | get_dict_value:"name_filter" }}">

                        </div>
                        <div class="col-md-5 mb-3">
                            <label for="gameclub">Klub</label>
                            <input type="text" class="form-control" id="gameclub"
                                   name="club_filter"
                                   value="{{ filter.data | get_dict_value:"club_filter" }}">

                        </div>
                    </div>
                    <div class="form-row d-flex justify-content-center">

                        <div class="col-md-3 mb-3">
                            <label for="tournamentdate">Data partii</label>
                            <input type="date" class="form-control" id="tournamentdate"
                                   name="date_filter"
                                   value="{{ filter.data | get_dict_value:"date_filter" }}">
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="tournamentcity">Nazwa turnieju</label>
                            <input type="text" class="form-control" id="tournamentcity"
                                   name="tournament__name"
                                   value="{{ filter.data | get_dict_value:"tournament__name" }}">

                        </div>
                        <div class="col-md-3 mb-3">

                            <label for="tournamenttype">Rodzaj partii</label>
                            <select class="custom-select" id="tournamenttype" name="tournament__type">
                                {% with filter_type_value=filter.data|get_dict_value:"tournament__type" %}
                                    {% for k, v in select_options.items %}
                                        <option value="{{ k }}"
                                                {% if filter_type_value == k %}
                                                selected="selected"
                                                {% endif %}>
                                            {{ v }}
                                        </option>
                                    {% endfor %}
                                {% endwith %}
                            </select>
                        </div>

                    </div>
                    <div class="form-row d-flex justify-content-center">
                        <button class="btn btn-info px-5" type="submit">Filtruj</button>&nbsp;
                        <a class="btn btn-outline-info px-5" href="{% url 'chess_viewer:index' %}">Wyczyść</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="list-group ">
        {% for game in object_list %}
            <a class="list-group-item list-group-item-action d-flex flex-row justify-content-between "
               href="{% url 'chess_viewer:game' game.id %}">
                <div id ="left" class="d-flex flex-column align-items-baseline">
                    <div class="">
                        <b> {{ game.white_player.first_name }} {{ game.white_player.last_name }}
                                    - {{ game.black_player.first_name }} {{ game.black_player.last_name }}
                            </b>
                    </div>
                    {% if game.preview %}
                        <div class=""> {{ game.preview |truncatechars:60 }}</div>
                    {% endif %}
                    {% if game.result is not None %}
                    <div class="badge badge-secondary">{% if game.result == 0 %}0:1
                        {% elif game.result == 0.5 %}&frac12;:&frac12;{% else %}1:0{% endif %}</div>
                    {% endif %}
                </div>

                {% if game.tournament %}
                <div id="right" class="d-flex flex-column align-items-end">
                    <div class=""><b>{{ game.tournament.name |truncatechars:100 }}</b></div>
                        {% if game.date %}
                            <div class=""><b>
                                    {{ game.date }}</b>
                            </div>
                        {% elif game.tournament.date %}
                            <div class=""><b>
                                {{ game.tournament.date }}</b>
                            </div>
                            {% else %}<div>&nbsp;</div>
                        {% endif %}
                    <div class="">
                        {% if game.tournament.type or game.tournament.time or game.tournament.time_add %}
                        <span class="badge badge-info">
                            {% if game.tournament.type == 's' %}szachy szybkie
                            {% elif game.tournament.type == 'b' %}szachy błyskawiczne
                            {% elif game.tournament.type == 'k' %}szachy klasyczne
                            {% endif %}
                            {% if game.tournament.type and game.tournament.time > 0 %} :
                                {% endif %}
                            {% if game.tournament.time > 0 %}
                                P{{ game.tournament.time | floatformat }}' {% if game.tournament.time_add > 0 %}+{{ game.tournament.time_add | floatformat }}'' {% endif %}
                            {% endif %}
                        </span>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </a>
        {% empty %}
            <div class="alert alert-danger text-center" role="alert">
                Nie znaleziono partii szachowych o zadanych kryteriach w bazie.
            </div>
        {% endfor %}

    </div>
    {% include "partial/pagination.html" %}
{% endblock %}

chess_app/templates/index.html
{% extends 'base.html' %}

{% block nav-index %}
    <a class="nav-link active" href="{% url 'chess_viewer:index' %}">Lista partii </a>
{% endblock %}

{% block content %}
    <div class="my-4">
    <span class="text-center">
    <h2 class="mb-3">Baza partii </h2>

    </span>
        <div class="card">
            <div class="card-body">
                <form novalidate>
                    <div class="form-row d-flex justify-content-center">
                        <div class="col-md-5 mb-3">
                            <label for="gamelastname">Nazwisko</label>
                            <input type="text" class="form-control" id="gamelastname" value="">

                        </div>
                        <div class="col-md-5 mb-3">
                            <label for="gameclub">Klub</label>
                            <input type="text" class="form-control" id="gameclub">

                        </div>
                    </div>
                    <div class="form-row d-flex justify-content-center">

                        <div class="col-md-3 mb-3">
                            <label for="tournamentdate">Data partii</label>
                            <input type="date" class="form-control" id="tournamentdate">

                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="tournamentcity">Nazwa turnieju</label>
                            <input type="text" class="form-control" id="tournamentcity">

                        </div>
                        <div class="col-md-3 mb-3">

                            <label for="tournamenttype">Rodzaj partii</label>
                            <select class="custom-select" id="tournamenttype">
                                <option selected value="">...</option>
                                <option>Klasyczna</option>
                                <option>Szybkia</option>
                                <option>Błyskawiczna</option>
                            </select>
                        </div>

                    </div>
                    <div class="form-row d-flex justify-content-center">
                        <button class="btn btn-info px-5" type="submit">Filtruj</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="list-group ">
        {% for game in object_list %}
            <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
               href="{% url 'chess_viewer:game' game.id %}">
            <span class="">
                <div class="">
                    <b> {{ game.white_player.first_name }} {{ game.white_player.last_name }}
                                - {{ game.black_player.first_name }} {{ game.black_player.last_name }}
                        </b>
                </div>
                {% if game.preview %}
                    <div class=""> {{ game.preview |truncatechars:60 }}</div>
                {% endif %}
                {% if game.result %}

                    <span class="badge badge-secondary">{% if game.result == 0 %}0:1
                        {% elif game.result == 0.5 %}&frac12;:&frac12;{% else %}1:0{% endif %}</span>
                {% endif %}
            </span>

                {% if game.tournament %}
                    <span class="text-right">
                <div class=""><b>{{ game.tournament.name |truncatechars:100 }}</b></div>
                <div class=""><b>
                    {% if game.tournament.date %}
                        {{ game.tournament.date }}{% endif %}</b>
                </div>
                <div class="">
                    <span class="badge badge-info">{% if tournament.type == 's' %}szachy szybkie:
                    {% elif tournament.type == 'b' %}szachy błyskawiczne: {% else %}szachy klasyczne: {% endif %}
                        {% if game.tournament.time and game.tournament.time_add %}
                            P{{ game.tournament.time | floatformat }}'+{{ game.tournament.time_add | floatformat }}''
                        {% endif %}
                    </span>
                </div>
            </span>
                {% endif %}
            </a>
        {% endfor %}

    </div>
    {% include "partial/pagination.html" %}
{% endblock %}

chess_app/templates/tournament.html
{%  extends 'base.html' %}

{% block title %}
    {{ object.name }}
{% endblock title %}

{% block content %}
    <div class="my-4">
    <span class="text-center">
    <h1 class="mb-3">{{ object.name }} </h1>

    {% if object.description  %} <div class="">{{ object.description }}</div> {% endif %}
    </span>

    </div>
    <table class="table">
      <tbody>
        {% if object.date is not None or object.city is not None %}
        <tr>
          <th scope="row"> Data i miejsce: </th>
          <td> {% if object.date%}{{ object.date }}{% endif %}
              {% if object.date and object.city %}, {% endif %}
              {% if object.city%}{{ object.city }}{% endif %} </td>
        </tr>
        {% endif %}
        {% if object.time > 0 and object.time_add is not None %}
        <tr>
          <th scope="row">Tempo gry:</th>
          <td>P{{ object.time | floatformat }}'+{{ object.time_add | floatformat }}''/pos.</td>
        </tr>
        {% endif %}
        {% if object.link %}
        <tr>
          <th scope="row">Więcej informacji o turnieju: </th>
          <td><a href="{{ object.link }}">{{ object.name }}</a></td>
        </tr>
      {% endif %}
      </tbody>
    </table>

        {% for round, games_round in object_list %}
            <div class="card text-center m-3">
            {%  if round != 0 %}
              <div class="card-header "><b>

            Runda {{ round }}</b>
              </div>
            {%  endif %}

            <div class="list-group">
            {% for game in games_round %}

                <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
                   href="{% url 'chess_viewer:game' game.id %}">
                    <span>
                    {%  if game.result is not None %}
                    <span class="badge badge-secondary">
                        {% if game.result == 0 %}0:1
                            {% elif game.result == 0.5 %}&frac12;:&frac12;{% else %}1:0{% endif %}</span>
                    {% endif %}
                        <b>
                            {{ game.white_player.first_name }} {{ game.white_player.last_name }}
                            - {{ game.black_player.first_name }} {{ game.black_player.last_name }} </b>
                    </span>
                    <span>
                         {{ game.preview | truncatechars:80 }}
                    </span>
                </a>

            {% endfor %}
            </div>

            </div>
        {% empty %}
        <div class="alert alert-info text-center" role="alert">
            Nie znaleziono partii z tego turnieju w bazie.
        </div>
        {%  endfor %}
        {% include "partial/pagination.html" %}
    <div class="text-center"><a class="btn btn-info m-3" href="{% url 'chess_viewer:tournaments' %}">Powrót do listy turniejów </a></div>


    {% endblock %}